language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
    - "pypy3"

matrix:
    allow_failures:
        - python: "pypy"
        - python: "pypy3"

install:
    - "python setup.py install"
    - "pip install pyte coverage"

script:
    - nosetests tests
