language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - "python setup.py install"
    - "pip install pyte coverage"
    - "pip install git+git://github.com/thomasballinger/wcwidth.git@fixes"

script:
    - nosetests tests
